include:
#- ./../../configs/hw/boards/pic32mz_memory.yml
- ./syms.yml

memory_map:
  sram:
    base_addr: 0x80000000
    permissions: rw-
    size: 0x80000
  text:
    base_addr: 0x9d000000
    file: ./STARTER-FreeRTOS-I2C.elf
    permissions: r-x
    size: 0x6000
    file_offset: 0x020000
  boot:
    base_addr: 0xbfc00000
    file: ./STARTER-FreeRTOS-I2C.elf
    permissions: r-x
    size: 0x1000
    file_offset: 0x040000
    is_entry: True
  mmio_1:
    base_addr: 0xbf800000
    size: 0x10000
    permissions: rw-
  mmio_2:
    base_addr: 0xbf811000
    size: 0xe9000
    permissions: rw-
  interrupt_control_registers:
    base_addr: 0xbf810000
    size: 0x1000
    permissions: rw-

handlers:
  skil_uart_write:
    addr: UART2_Write 
interrupt_triggers:
  idle_irq:
    every_nth_tick: 0x200
    fuzz_mode: round_robin 

use_nvic: true 
use_timer: true
nvic:
  vtor: 0
  num_vecs: 256
  processor: pic32mz  


 
arch: MIPS32
endianness: LE
initial_sp: 0x8007FFF0
entry_point: 0xbfc00000

use_systick: false

