include:
- ./syms.yml

memory_map:
  sram:
    base_addr: 0x80000000
    file: ./StarterKit-Task4.elf
    permissions: rw-
    size: 0x80000
  text:
    base_addr: 0x9d000000
    file: ./StarterKit-Task4.elf
    permissions: r-x
    size: 0x5000
    file_offset: 0x020000
  boot:
    base_addr: 0xbfc00000
    file: ./StarterKit-Task4.elf
    permissions: r-x
    size: 0x1000
    file_offset: 0x040000
    is_entry: True
#  mmio: 
#    base_addr:  0xbf800000
#    size: 0x100000
#    permissions: rw-
# due to PIC32MZ utilizing interrupt registers in a partion of peripheral MMIO range for interrupt vector addressing
# the proper set-up should exclude the MMIO range (0xbf810000 + 0x1000)  
  mmio_1:
    base_addr: 0xbf800000
    size: 0x10000
    permissions: rw-
  mmio_2:
    base_addr: 0xbf811000
    size: 0xe9000
    permissions: rw-
  interrupt_control_registers:
    base_addr: 0xbf810000
    size: 0x1000
    permissions: rw-

interrupt_triggers:
  switch_press:
    every_nth_tick: 0x400
    irq: 119
  timer_tick:
    every_nth_tick: 0x200
    irq: 4

handlers:
  UART2_Write:
    handler: fuzzware_harness.user_hooks.generic.stdio.UART_Write
  


use_nvic: true  
nvic:
  # interrupt vector base address (alternative name: 'addr')
  vtor: 0
  # configure the maximum number of vectors in the nvic, defaults to 256
  num_vecs: 256
  processor: pic32mz   
  #disabled_irqs: [145] 

arch: MIPS32
endianness: LE
initial_sp: 0x8007fff8
entry_point: 0xbfc00000

# use_timers: false
# use_nvic: false
use_systick: false
