files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mx_xlp_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: 7AFE82F3B7C35BD184FCBD6E3FD79B4D
  logicalPath: config/pic32mx_xlp_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7AFE82F3B7C35BD184FCBD6E3FD79B4D
- generatedChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
  logicalPath: config/pic32mx_xlp_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
- generatedChecksum: null
  logicalPath: ''
  name: main_pic32mx_xlp.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 7CC8560EFD14237B4627CB2128CE4836
  logicalPath: config/pic32mx_xlp_sk/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7CC8560EFD14237B4627CB2128CE4836
- generatedChecksum: 36F718A0C383C0856EB1DE4DEA41B4D5
  logicalPath: config/pic32mx_xlp_sk/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 36F718A0C383C0856EB1DE4DEA41B4D5
- generatedChecksum: 19B28B1F72C9735F041CFB7B868285C8
  logicalPath: config/pic32mx_xlp_sk/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 19B28B1F72C9735F041CFB7B868285C8
- generatedChecksum: E0007C12D194A126ED2EA73E1A25FBC0
  logicalPath: config/pic32mx_xlp_sk/peripheral/icap
  name: plib_icap2.c
  physicalPath: peripheral/icap
  security: NON_SECURE
  type: SOURCE
  userChecksum: E0007C12D194A126ED2EA73E1A25FBC0
- generatedChecksum: 8C9CC794BA3FBB9DC2B88D268BFC2010
  logicalPath: config/pic32mx_xlp_sk/peripheral/ocmp
  name: plib_ocmp2.c
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8C9CC794BA3FBB9DC2B88D268BFC2010
- generatedChecksum: 45F8FF1EAE32DDB62B2FC6869551F69A
  logicalPath: config/pic32mx_xlp_sk/peripheral/tmr
  name: plib_tmr2.c
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: 45F8FF1EAE32DDB62B2FC6869551F69A
- generatedChecksum: 8A8E4B7D1561E11086D51E8925F8F77E
  logicalPath: config/pic32mx_xlp_sk/peripheral/uart
  name: plib_uart1.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8A8E4B7D1561E11086D51E8925F8F77E
- generatedChecksum: 42A948E504602741B0D592C55FCD9A7B
  logicalPath: config/pic32mx_xlp_sk/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 42A948E504602741B0D592C55FCD9A7B
- generatedChecksum: 05B87575C486C830091CA07E3551C2C3
  logicalPath: config/pic32mx_xlp_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 05B87575C486C830091CA07E3551C2C3
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mx_xlp_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mx_xlp_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mx_xlp_sk/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 3BE6DA6B5D6D8605EC41BCB0DF5C8C7A
  logicalPath: config/pic32mx_xlp_sk/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 3BE6DA6B5D6D8605EC41BCB0DF5C8C7A
- generatedChecksum: 9C0A5076C32650BA16169CCEEB2C4EF2
  logicalPath: config/pic32mx_xlp_sk/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 9C0A5076C32650BA16169CCEEB2C4EF2
- generatedChecksum: 65FE0AB9A095284AE21ED5430B5A4CEE
  logicalPath: config/pic32mx_xlp_sk/peripheral/icap
  name: plib_icap2.h
  physicalPath: peripheral/icap
  security: NON_SECURE
  type: HEADER
  userChecksum: 65FE0AB9A095284AE21ED5430B5A4CEE
- generatedChecksum: B75BC5AEF7A117FB761A3A8548E16E3D
  logicalPath: config/pic32mx_xlp_sk/peripheral/icap
  name: plib_icap_common.h
  physicalPath: peripheral/icap
  security: NON_SECURE
  type: HEADER
  userChecksum: B75BC5AEF7A117FB761A3A8548E16E3D
- generatedChecksum: BA6573B1C4A99A2D0181397BE068B9EB
  logicalPath: config/pic32mx_xlp_sk/peripheral/ocmp
  name: plib_ocmp2.h
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: HEADER
  userChecksum: BA6573B1C4A99A2D0181397BE068B9EB
- generatedChecksum: C7376B9C0FE98B35880E7395A16846B2
  logicalPath: config/pic32mx_xlp_sk/peripheral/ocmp
  name: plib_ocmp_common.h
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: HEADER
  userChecksum: C7376B9C0FE98B35880E7395A16846B2
- generatedChecksum: 9DF2058BBA7397756E0CED63F294C4C3
  logicalPath: config/pic32mx_xlp_sk/peripheral/tmr
  name: plib_tmr2.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: 9DF2058BBA7397756E0CED63F294C4C3
- generatedChecksum: D948F2CE092CAB556EF299D3CCD83A55
  logicalPath: config/pic32mx_xlp_sk/peripheral/tmr
  name: plib_tmr_common.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: D948F2CE092CAB556EF299D3CCD83A55
- generatedChecksum: 6688F1ADA16F2A2759A3C2D93250963D
  logicalPath: config/pic32mx_xlp_sk/peripheral/uart
  name: plib_uart1.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 6688F1ADA16F2A2759A3C2D93250963D
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mx_xlp_sk/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/pic32mx_xlp_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: CF99597DFF6AD85206D19812D9D7793C
  logicalPath: config/pic32mx_xlp_sk
  name: p32MX274F256D.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: CF99597DFF6AD85206D19812D9D7793C
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_xlp_sk;
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_xlp_sk;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
