files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mx_xlp_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: EFB92AB69C449023E2B49913EC2C9B0E
  logicalPath: config/pic32mx_xlp_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: EFB92AB69C449023E2B49913EC2C9B0E
- generatedChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
  logicalPath: config/pic32mx_xlp_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
- generatedChecksum: null
  logicalPath: ''
  name: main_pic32mx.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: A641CCC246B93D7058103C491C6062CA
  logicalPath: config/pic32mx_xlp_sk/peripheral/adc
  name: plib_adc.c
  physicalPath: peripheral/adc
  security: NON_SECURE
  type: SOURCE
  userChecksum: A641CCC246B93D7058103C491C6062CA
- generatedChecksum: 9FE89FAEFC8F4479ECFC1AA824CB7D09
  logicalPath: config/pic32mx_xlp_sk/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9FE89FAEFC8F4479ECFC1AA824CB7D09
- generatedChecksum: 36F718A0C383C0856EB1DE4DEA41B4D5
  logicalPath: config/pic32mx_xlp_sk/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 36F718A0C383C0856EB1DE4DEA41B4D5
- generatedChecksum: 95087D84A3D34F60355B692179D260E8
  logicalPath: config/pic32mx_xlp_sk/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 95087D84A3D34F60355B692179D260E8
- generatedChecksum: 8A8E4B7D1561E11086D51E8925F8F77E
  logicalPath: config/pic32mx_xlp_sk/peripheral/uart
  name: plib_uart1.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 8A8E4B7D1561E11086D51E8925F8F77E
- generatedChecksum: 42A948E504602741B0D592C55FCD9A7B
  logicalPath: config/pic32mx_xlp_sk/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 42A948E504602741B0D592C55FCD9A7B
- generatedChecksum: 08C7B9FCE201420DFF712F563B41C450
  logicalPath: config/pic32mx_xlp_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 08C7B9FCE201420DFF712F563B41C450
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mx_xlp_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mx_xlp_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: AB5C9235C0925206C325243F3A9E0EB5
  logicalPath: config/pic32mx_xlp_sk/peripheral/adc
  name: plib_adc.h
  physicalPath: peripheral/adc
  security: NON_SECURE
  type: HEADER
  userChecksum: AB5C9235C0925206C325243F3A9E0EB5
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mx_xlp_sk/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 3BE6DA6B5D6D8605EC41BCB0DF5C8C7A
  logicalPath: config/pic32mx_xlp_sk/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 3BE6DA6B5D6D8605EC41BCB0DF5C8C7A
- generatedChecksum: 9C0A5076C32650BA16169CCEEB2C4EF2
  logicalPath: config/pic32mx_xlp_sk/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 9C0A5076C32650BA16169CCEEB2C4EF2
- generatedChecksum: 6688F1ADA16F2A2759A3C2D93250963D
  logicalPath: config/pic32mx_xlp_sk/peripheral/uart
  name: plib_uart1.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 6688F1ADA16F2A2759A3C2D93250963D
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config/pic32mx_xlp_sk/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/pic32mx_xlp_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: CF99597DFF6AD85206D19812D9D7793C
  logicalPath: config/pic32mx_xlp_sk
  name: p32MX274F256D.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: CF99597DFF6AD85206D19812D9D7793C
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_xlp_sk;
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_xlp_sk;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
