files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mx_xlp_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: 3B78437513353EF967A006EA51B46541
  logicalPath: config/pic32mx_xlp_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3B78437513353EF967A006EA51B46541
- generatedChecksum: 20F22B70C4B0B528FEFE85C97C72531F
  logicalPath: config/pic32mx_xlp_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 20F22B70C4B0B528FEFE85C97C72531F
- generatedChecksum: null
  logicalPath: ''
  name: main_pic32mz_ef_sk.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 00D75E51D7E1A9846715310BD13EB3B6
  logicalPath: config/pic32mx_xlp_sk/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 00D75E51D7E1A9846715310BD13EB3B6
- generatedChecksum: CDE489012C46160ED6A67092B2FFCE99
  logicalPath: config/pic32mx_xlp_sk/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: CDE489012C46160ED6A67092B2FFCE99
- generatedChecksum: 648D3B13F6BFF0A300471D955302CC32
  logicalPath: config/pic32mx_xlp_sk/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 648D3B13F6BFF0A300471D955302CC32
- generatedChecksum: 1FB7E6EB017BEB44D81A7FB4ABFB632D
  logicalPath: config/pic32mx_xlp_sk/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1FB7E6EB017BEB44D81A7FB4ABFB632D
- generatedChecksum: 71352EF41F6688AD8408E42970B50B66
  logicalPath: config/pic32mx_xlp_sk/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 71352EF41F6688AD8408E42970B50B66
- generatedChecksum: 926B3884C37391D6A7B81BA187A88996
  logicalPath: config/pic32mx_xlp_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 926B3884C37391D6A7B81BA187A88996
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mx_xlp_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mx_xlp_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mx_xlp_sk/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 140E912AD4C9D114D0D0305FD44F075F
  logicalPath: config/pic32mx_xlp_sk/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: 140E912AD4C9D114D0D0305FD44F075F
- generatedChecksum: 3BE6DA6B5D6D8605EC41BCB0DF5C8C7A
  logicalPath: config/pic32mx_xlp_sk/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 3BE6DA6B5D6D8605EC41BCB0DF5C8C7A
- generatedChecksum: 44258951E7D0259ED367B5E21A540236
  logicalPath: config/pic32mx_xlp_sk/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 44258951E7D0259ED367B5E21A540236
- generatedChecksum: 7DC91D6D376C98802C9C2990432DE9B7
  logicalPath: config/pic32mx_xlp_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7DC91D6D376C98802C9C2990432DE9B7
- generatedChecksum: CF99597DFF6AD85206D19812D9D7793C
  logicalPath: config/pic32mx_xlp_sk
  name: p32MX274F256D.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: CF99597DFF6AD85206D19812D9D7793C
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_xlp_sk;
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_xlp_sk;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
