format_version: v1.0
type: UniqueComponent
attributes: {id: adc}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: AD1CHS__CH0SA}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '7'}
  - type: Boolean
    attributes: {id: AD1CON1__ASAM}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: AD1CON1__CLRASAM}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: Hex
    attributes: {id: ADC_AD1CHS}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc, value: '458752'}
  - type: Hex
    attributes: {id: ADC_AD1CON1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc, value: '4'}
  - type: Boolean
    attributes: {id: ADC_INTERRUPT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Float
    attributes: {id: ADC_TCLK}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: adc, value: '166.0'}
- type: ElementPosition
  attributes: {x: '31', y: '60', id: adc}
