configName: pic32mx_usb_sk3
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: PIC32MX470F512L
projectName: ''
settings:
  PackageFilter: csp;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\PIC32MX_DFP\1.0.49\atdf\PIC32MX470F512L.atdf
