format_version: v1.0
type: UniqueComponent
attributes: {id: ebi}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: CFGEBIA_EBIADD}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '19'}
  - type: Boolean
    attributes: {id: CFGEBIC_EBIBSEN0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: CFGEBIC_EBIBSEN1}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: CFGEBIC_EBICSEN0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: KeyValueSet
    attributes: {id: CFGEBIC_EBIDAT}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Boolean
    attributes: {id: CFGEBIC_EBIDAT0}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ebi, value: 'true'}
  - type: Boolean
    attributes: {id: CFGEBIC_EBIDAT1}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ebi, value: 'true'}
  - type: Boolean
    attributes: {id: CFGEBIC_EBIOEEN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Boolean
    attributes: {id: CFGEBIC_EBIWEEN}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'true'}
  - type: Hex
    attributes: {id: CFGEBIC_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ebi, value: '13075'}
  - type: Hex
    attributes: {id: EBICS0_CSADDR}
    children:
    - type: Attributes
      children:
      - type: Boolean
        attributes: {id: visible}
        children:
        - {type: Value, value: 'true'}
  - type: KeyValueSet
    attributes: {id: EBIMSK0_MEMSIZE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '6'}
  - type: Hex
    attributes: {id: EBIMSK0_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ebi, value: '38'}
  - type: KeyValueSet
    attributes: {id: EBISMCON_SMDWIDTH0}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Hex
    attributes: {id: EBISMCON_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ebi, value: '1'}
  - type: Integer
    attributes: {id: EBISMT0_TAS}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Integer
    attributes: {id: EBISMT0_TBTA}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Integer
    attributes: {id: EBISMT0_TPRC}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: Integer
    attributes: {id: EBISMT0_TRC}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '2'}
  - type: Integer
    attributes: {id: EBISMT0_TWP}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '10'}
  - type: Hex
    attributes: {id: EBISMT0_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: ebi, value: '10626'}
- type: ElementPosition
  attributes: {x: '347', y: '22', id: ebi}
