format_version: v1.0
type: UniqueComponent
attributes: {id: icap1}
children:
- type: Symbols
  children:
  - type: KeyValueSet
    attributes: {id: ICAP_ICxCON_ICI}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '0'}
  - type: KeyValueSet
    attributes: {id: ICAP_ICxCON_ICTMR}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: '1'}
  - type: Boolean
    attributes: {id: ICAP_INTERRUPT_ENABLE}
    children:
    - type: Values
      children:
      - type: User
        attributes: {value: 'false'}
  - type: Hex
    attributes: {id: ICxCON_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: icap1, value: '129'}
- type: ElementPosition
  attributes: {x: '21', y: '71', id: icap1}
